Update install (WIP)

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -31,6 +31,9 @@ source /usr/share/yunohost/helpers
 #
 
 admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
+secret_key="$(ynh_string_random --length=32)"
+ynh_app_setting_set --app=$app --key=secret_key --value="$secret_key"
+
 
 #=================================================
 # APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
@@ -57,18 +60,15 @@ chown -R $app:www-data "$install_dir"
 #=================================================
 
 ynh_script_progression --message="Build project using pip, migrate and create admin" --weight=1
-ynh_print_info --message="$(ls -ld $data_dir)"
 ynh_exec_as $app /usr/bin/python3 -m venv "${data_dir}/hc-venv"
 
 sudo -s -u $app -- <<EOF
     source "${data_dir}/hc-venv/bin/activate"
 
     pip3 install wheel setuptools
-    pip3 install -r "$install_dir/requirements.txt"
+    cd $install_dir
+    pip3 install -r "./requirements.txt"
 
-    python3 ./manage.py migrate --no-input
-    export DJANGO_SUPERUSER_PASSWORD=$(ynh_string_random)
-    python3 ./manage.py createsuperuser --username="$admin" --email="$admin_mail"
 EOF
 
 #=================================================
@@ -143,7 +143,8 @@ yunohost service add $app --description="A cron monitoring tool written in Pytho
 ynh_use_logrotate
 
 # Create a dedicated Fail2Ban config
-ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"
+# FIXME
+# ynh_add_fail2ban_config --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"
 
 #=================================================
 # APP INITIAL CONFIGURATION
@@ -164,17 +165,17 @@ ynh_script_progression --message="Adding a configuration file..." --weight=1
 ###
 ### Check the documentation of `ynh_add_config` for more info.
 
-ynh_add_config --template="env" --destination="$install_dir/env"
+ynh_add_config --template="env" --destination="$install_dir/.env"
 
 # FIXME: this should be handled by the core in the future
 # You may need to use chmod 600 instead of 400,
 # for example if the app is expected to be able to modify its own config
-chmod 400 "$install_dir/env"
-chown $app:$app "$install_dir/env"
+chmod 400 "$install_dir/.env"
+chown $app:$app "$install_dir/.env"
 
-ynh_add_config --template="custom_env" --destination="$data_dir/env"
-chmod 600 "$data_dir/env"
-chown $app:$app "$data_dir/env"
+ynh_add_config --template="custom_env" --destination="$data_dir/.env"
+chmod 600 "$data_dir/.env"
+chown $app:$app "$data_dir/.env"
 
 ### For more complex cases where you want to replace stuff using regexes,
 ### you shoud rely on ynh_replace_string (which is basically a wrapper for sed)
@@ -184,31 +185,29 @@ chown $app:$app "$data_dir/env"
 ### ynh_store_file_checksum --file="$install_dir/some_config_file"
 
 #=================================================
-# SETUP APPLICATION WITH CURL
-#=================================================
-
-### Use these lines only if the app installation needs to be finalized through
-### web forms. We generally don't want to ask the final user,
-### so we're going to use curl to automatically fill the fields and submit the
-### forms.
-
-# Installation with curl
-ynh_script_progression --message="Finalizing installation..." --weight=1
-ynh_local_curl "/INSTALL_PATH" "key1=value1" "key2=value2" "key3=value3"
-
-#=================================================
 # GENERIC FINALIZATION
-#=================================================
-# RUN TESTS
 #=================================================
 
 ynh_script_progression --message="Running tests before starting app..." --weight=1
 
-ynh_exec_as $app '
+sudo -s -u $app -- <<EOF
+    set -eux -o pipefail
     source "${data_dir}/hc-venv/bin/activate"
 
+    set -a
+    source $install_dir/.env
+    set +a
+    cd $install_dir
+
+    python3 ./manage.py migrate
+    python3 ./manage.py yunohost_create_superuser --username="$admin" --email="${admin_mail}"
+    python3 ./manage.py collectstatic
+    python3 ./manage.py compress
+
+    export DB_PASSWORD="$(cat $PSQL_ROOT_PWD_FILE)"
+    export DB_USER=postgres
     python3 ./manage.py test
-'
+EOF
 
 #=================================================
 # START SYSTEMD SERVICE
